version: '3.0'
services:
  falador-mongodb:
    container_name: falador-mongodb
    image: library/mongo:4.0
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
